# Configuration variables
docker: true
gaymer: false
hide_libreoffice: true
kicad: true
latex: true
tailscale: true
vfio_ids:
  - 10de:10f8
  - 10de:1ad8
  - 10de:1ad9
  - 10de:1eb1
  - 1b73:1100
virtualization: true
vscode: true
zsh: true
