- name: Configure Fedora Workstation install
  hosts: localhost
  become: true

  pre_tasks:
    - name: Load configuration variables
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml 

    - name: Update DNF cache
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        update_cache: true
  
  tasks:
    - name: Fedora setup
      when: >
        (ansible_distribution == 'Fedora')
      block:
        - name: Set up DNF
          ansible.builtin.import_tasks: tasks/dnf.yml

        - name: Install VS Code
          ansible.builtin.import_tasks: tasks/vscode.yml
          when: vscode

        - name: Install Tailscale
          ansible.builtin.import_tasks: tasks/tailscale.yml
          when: tailscale

        - name: Install Steam
          ansible.builtin.import_tasks: tasks/steam.yml
          when: gaymer

        - name: Install libvirt, add user to libvirt group
          ansible.builtin.import_tasks: tasks/virtualization.yml
          when: virtualization
        
        - name: Install Packages
          ansible.builtin.import_tasks: tasks/packages.yml
    
    - name: Set up i2c group, add user to i2c
      ansible.builtin.import_tasks: tasks/i2c.yml

- name: OS independent configuration
  hosts: localhost
  become: false

  pre_tasks:
    - name: Load configuration variables
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml 

  tasks:  
    - name: Check if vscode installed and in path
      ansible.builtin.command: which code
      check_mode: false
      changed_when: false
      failed_when: code_installed.rc > 1
      register: code_installed

    - name: Configure vscode for user
      ansible.builtin.import_tasks: tasks/vscode-user.yml
      when: vscode and (code_installed.rc == 0)
    
    - name: Get current desktop
      ansible.builtin.set_fact:
        desktop: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"

    - name: Configure LibreOffice
      ansible.builtin.import_tasks: tasks/libreoffice.yml
          
    - name: Configure Gnome
      when: desktop == "GNOME"
      ansible.builtin.include_tasks: tasks/gnome.yml
    
    - name: Configure ptyxis
      when: desktop == "GNOME"
      ansible.builtin.include_tasks: tasks/ptyxis.yml
    
    - name: Configure zsh
      ansible.builtin.import_tasks: tasks/zsh.yml
      when: zsh
