- name: OS independent configuration
  hosts: localhost
  become: false

  pre_tasks:
    - name: Load configuration variables
      ansible.builtin.include_vars: "{{ item }}"
      loop:
        - config.yml 

  tasks:  
    - name: Get current desktop
      ansible.builtin.set_fact:
        desktop: "{{ lookup('env', 'XDG_CURRENT_DESKTOP') }}"

    - name: Configure ptyxis
      when: desktop == "GNOME"
      ansible.builtin.include_tasks: tasks/ptyxis.yml
    
