- name: Configure DNF max_parallel_downloads
  ansible.builtin.lineinfile:
    dest: "/etc/dnf/dnf.conf"
    regexp: "^max_parallel_downloads"
    line: "max_parallel_downloads=10"
    
- name: Remove unnecessary preinstalled DNF packages
  ansible.builtin.dnf:
    state: removed
    name:
      - gnome-characters
      - gnome-connections
      - gnome-contacts
      - gnome-clocks
      - gnome-fonts
      - gnome-maps
      - gnome-photos
      - totem
      - mediawriter
      - gnome-boxes
      - yelp
      - rhythmbox
      - cheese
      - gnome-tour
      - gnome-text-editor

- name: Remove LibreOffice packages
  ansible.builtin.dnf:
    state: removed
    name:
      - libreoffice-calc
      - libreoffice-core
      - libreoffice-data
      - libreoffice-emailmerge
      - libreoffice-filters
      - libreoffice-graphicfilter
      - libreoffice-gtk3
      - libreoffice-gtk4
      - libreoffice-help-en
      - libreoffice-impress
      - libreoffice-langpack-en
      - libreoffice-ogltrans
      - libreoffice-opensymbol-fonts
      - libreoffice-pdfimport
      - libreoffice-pyuno
      - libreoffice-ure
      - libreoffice-ure-common
      - libreoffice-writer
      - libreoffice-x11
      - libreoffice-xsltfilter

- name: Install distribution-gpg-keys
  ansible.builtin.dnf:
    name: distribution-gpg-keys
    update_cache: true

- name: Import RPM Fusion keys
  ansible.builtin.rpm_key:
    state: present
    key: "{{ item }}"
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020"
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020"

- name: Enable the RPM Fusion repositories
  dnf:
    name: 
      - "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present

- name: Update all DNF packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: yes