- name: Create i2c group
  ansible.builtin.group:
    name: i2c
    state: present

- name: Add user to i2c group
  ansible.builtin.user:
    append: true
    name: "{{ lookup('env', 'USER') }}"
    groups: i2c

- name: Copy udev rule
  ansible.builtin.copy:
    src: 10-local_i2c_group.rules
    dest: /etc/udev/rules.d/10-local_i2c_group.rules
    owner: root
    group: root
    mode: '0755'