- name: Install development packages
  ansible.builtin.dnf:
    name:
      - ansible
      - avrdude
      - avr-binutils
      - avr-gcc
      - avr-libc
      - gcc
      - gcc-c++
      - git
      - python3
      - python3-pip
      - java-latest-openjdk
      - ant
      - ant-junit
      - sqlite

- name: Install Gnome and useful Linux packages
  ansible.builtin.dnf:
    name:
      - ddcutil
      - dnf5
      - entr
      - geary
      - gnome-extensions-app
      - gnome-shell-extension-caffeine
      - gnome-tweaks
      - htop
      - libheif
      - lm_sensors
      - prename
      - python3-pytest-xdist+psutil
      - remmina
      - screen
      - sqlite
      - tmux
      - util-linux
      - util-linux-user
      - vim
      - virt-manager
      - xclip
      - zsh

- name: Install ffmpeg and video drivers/codec
  ansible.builtin.dnf:
    name:
      - ffmpeg
      - ffmpeg-devel
      - ffmpeg-libs
      - intel-media-driver
      - libavcodec-freeworld
    update_cache: true
    allowerasing: true

- name: Install KiCad
  when: kicad
  ansible.builtin.dnf:
    name:
      - kicad
      - kicad-packages3d

- name: Install LaTeX packages
  when: latex
  ansible.builtin.dnf:
    name:
      - texlive-tabularray
      - texlive-ninecolors
      - texlive-algorithm2e
      - texlive-algorithms
      - texlive-alphalph
      - texlive-amscls
      - texlive-amsfonts
      - texlive-amsmath
      - texlive-atbegshi
      - texlive-attachfile
      - texlive-atveryend
      - texlive-auto-pst-pdf
      - texlive-auxhook
      - texlive-avantgar
      - texlive-babel
      - texlive-babelbib
      - texlive-base
      - texlive-bera
      - texlive-biblatex
      - texlive-bibtex
      - texlive-bidi
      - texlive-bigintcalc
      - texlive-bitset
      - texlive-bookman
      - texlive-bookmark
      - texlive-booktabs
      - texlive-boondox
      - texlive-breakurl
      - texlive-caption
      - texlive-carlisle
      - texlive-catchfile
      - texlive-changepage
      - texlive-charter
      - texlive-circuitikz
      - texlive-cite
      - texlive-cm
      - texlive-cmextra
      - texlive-cm-super
      - texlive-collection-basic
      - texlive-collection-fontsrecommended
      - texlive-colorprofiles
      - texlive-colortbl
      - texlive-courier
      - texlive-csquotes
      - texlive-ctablestack
      - texlive-currfile
      - texlive-dehyph
      - texlive-dvipdfmx
      - texlive-dvips
      - texlive-ec
      - texlive-enctex
      - texlive-enumitem
      - texlive-enumitem
      - texlive-epstopdf-pkg
      - texlive-eso-pic
      - texlive-etex
      - texlive-etexcmds
      - texlive-etex-pkg
      - texlive-etoolbox
      - texlive-euenc
      - texlive-euro
      - texlive-euro-ce
      - texlive-eurosym
      - texlive-everyshi
      - texlive-fancyhdr
      - texlive-fancyvrb
      - texlive-filecontents
      - texlive-filehook
      - texlive-float
      - texlive-fontaxes
      - texlive-fontspec
      - texlive-footmisc
      - texlive-fp
      - texlive-fpl
      - texlive-geometry
      - texlive-gettitlestring
      - texlive-glyphlist
      - texlive-graphics
      - texlive-graphics-cfg
      - texlive-graphics-def
      - texlive-grfext
      - texlive-grffile
      - texlive-gsftopk
      - texlive-helvetic
      - texlive-hobsub
      - texlive-hologo
      - texlive-hycolor
      - texlive-hyperref
      - texlive-hyphen-base
      - texlive-hyphenex
      - texlive-hyph-utf8
      - texlive-IEEEtran
      - texlive-ifmtarg
      - texlive-ifplatform
      - texlive-iftex
      - texlive-import
      - texlive-index
      - texlive-infwarerr
      - texlive-intcalc
      - texlive-kantlipsum
      - texlive-karnaugh
      - texlive-karnaugh-map
      - texlive-kastrup
      - texlive-knuth-lib
      - texlive-knuth-local
      - texlive-koma-script
      - texlive-kpathsea
      - texlive-kvdefinekeys
      - texlive-kvoptions
      - texlive-kvsetkeys
      - texlive-l3backend
      - texlive-l3kernel
      - texlive-l3packages
      - texlive-latex
      - texlive-latexconfig
      - texlive-latex-fonts
      - texlive-letltxmacro
      - texlive-lib
      - texlive-lipsum
      - texlive-listings
      - texlive-lm
      - texlive-lm-math
      - texlive-logreq
      - texlive-ltxcmds
      - texlive-lua-alt-getopt
      - texlive-luabidi
      - texlive-luahbtex
      - texlive-lualatex-math
      - texlive-lualibs
      - texlive-luaotfload
      - texlive-luatex
      - texlive-luatexbase
      - texlive-makecmds
      - texlive-makeindex
      - texlive-manfnt-font
      - texlive-marginnote
      - texlive-marvosym
      - texlive-mathpazo
      - texlive-mathtools
      - texlive-mdframed
      - texlive-memoir
      - texlive-metafont
      - texlive-mflogo
      - texlive-mflogo-font
      - texlive-mfware
      - texlive-microtype
      - texlive-minted
      - texlive-modes
      - texlive-mparhack
      - texlive-ms
      - texlive-multido
      - texlive-multirow
      - texlive-natbib
      - texlive-ncntrsbk
      - texlive-needspace
      - texlive-newtx
      - texlive-ntheorem
      - texlive-oberdiek
      - texlive-palatino
      - texlive-paralist
      - texlive-parallel
      - texlive-pdfcolmk
      - texlive-pdfescape
      - texlive-pdftex
      - texlive-pdftexcmds
      - texlive-pgf
      - texlive-picture
      - texlive-placeins
      - texlive-plain
      - texlive-polyglossia
      - texlive-psnfss
      - texlive-pst-3d
      - texlive-pst-coil
      - texlive-pst-eps
      - texlive-pst-fill
      - texlive-pst-grad
      - texlive-pst-math
      - texlive-pst-node
      - texlive-pst-ovl
      - texlive-pst-plot
      - texlive-pstricks
      - texlive-pstricks-add
      - texlive-pst-text
      - texlive-pst-tools
      - texlive-pst-tree
      - texlive-pxfonts
      - texlive-qstest
      - texlive-ragged2e
      - texlive-refcount
      - texlive-rerunfilecheck
      - texlive-rsfs
      - texlive-sauerj
      - texlive-selinput
      - texlive-setspace
      - texlive-showexpl
      - texlive-siunitx
      - texlive-soul
      - texlive-stringenc
      - texlive-subfig
      - texlive-symbol
      - texlive-tex
      - texlive-tex-gyre
      - texlive-tex-gyre-math
      - texlive-tex-ini-files
      - texlive-texlive-common-doc
      - texlive-texlive-en
      - texlive-texlive-msg-translations
      - texlive-texlive-scripts
      - texlive-thumbpdf
      - texlive-times
      - texlive-tipa
      - texlive-titlesec
      - texlive-tools
      - texlive-translator
      - texlive-txfonts
      - texlive-ucharcat
      - texlive-underscore
      - texlive-unicode-data
      - texlive-unicode-math
      - texlive-uniquecounter
      - texlive-url
      - texlive-utopia
      - texlive-varwidth
      - texlive-wasy
      - texlive-wasysym
      - texlive-wasy-type1
      - texlive-wrapfig
      - texlive-xcolor
      - texlive-xdvi
      - texlive-xetex
      - texlive-xetexconfig
      - texlive-xifthen
      - texlive-xkeyval
      - texlive-xpatch
      - texlive-xstring
      - texlive-xunicode
      - texlive-zapfchan
      - texlive-zapfding
      - texlive-zref
      - texlive-blindtext
      - texlive-pgfplots
      - texlive-pgfplots-doc
      - texlive-standalone
      - texlive-csvsimple
      - texlive-csvsimple-doc
      - texlive-ulem
      - texlive-ulem-doc
      - texlive-datetime2
      - texlive-makecell
      - texlive-makecell-doc

- name: Add Flathub remote
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo

- name: Install Flatpak applications
  become: false
  community.general.flatpak:
    name:
      - cc.arduino.IDE2
      - com.discordapp.Discord
      - com.github.tchx84.Flatseal
      - com.prusa3d.PrusaSlicer
      - org.videolan.VLC
      - us.zoom.Zoom
      - org.musicbrainz.Picard
