- name: Add Tailscale repo (Fedora)
  ansible.builtin.shell: "sudo dnf config-manager addrepo --from-repofile='https://pkgs.tailscale.com/stable/fedora/tailscale.repo'"

- name: Install Tailscale 
  ansible.builtin.dnf:
    name:
      - tailscale

- name: Enable tailscaled
  ansible.builtin.systemd_service:
    name: tailscaled
    state: started
    enabled: true
