- name: Import Microsoft signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: Configure VS Code repo file
  ansible.builtin.template:
    src: vscode.repo
    dest: "/etc/yum.repos.d/vscode.repo"
    owner: root
    group: root
    mode: '0644'

- name: Install VS Code
  ansible.builtin.dnf:
    name: code
    update_cache: true

- name: Create .config/Code/User directory
  become: false
  ansible.builtin.file:
    path: "{{ lookup('env', 'HOME') }}/.config/Code/User"
    state: directory

- name: Configure VS Code appearance (settings.json)
  ansible.builtin.template:
    src: settings.json
    dest: "{{ lookup('env', 'HOME') }}/.config/Code/User/settings.json"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0644'

- name: Configure VS Code keyboard shortcut
  ansible.builtin.template:
    src: keybindings.json
    dest: "{{ lookup('env', 'HOME') }}/.config/Code/User/keybindings.json"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0644'

- name: HiDPI tweaks for Wayland
  when: vscodeHiDPI
  ansible.posix.synchronize:
    src: "./templates/code-HiDPI/"
    dest: "{{ lookup('env', 'HOME') }}/.local/share/applications"
    recursive: true
