- name: Import Microsoft signing key
  ansible.builtin.rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc
- name: Configure VS Code repo file
  ansible.builtin.template:
    src: vscode.repo
    dest: "/etc/yum.repos.d/vscode.repo"
    owner: root
    group: root
    mode: '0644'
- name: Install VS Code
  ansible.builtin.dnf:
    name: code
    update_cache: true