- name: "zsh: oh-my-zsh"
  become: false
  ansible.builtin.git:
    repo: "https://github.com/ohmyzsh/ohmyzsh"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh"

- name: "zsh: zsh-autosuggestions"
  become: false
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-autosuggestions"

- name: "zsh: zsh-syntax-highlighting"
  become: false
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: "{{ lookup('env', 'HOME') }}/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"

# Conf files
- name: Copy .zshrc
  ansible.builtin.template:
    src: "zshrc"
    dest: "{{ lookup('env', 'HOME') }}/.zshrc"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
- name: Copy .vimrc
  ansible.builtin.template:
    src: "vimrc"
    dest: "{{ lookup('env', 'HOME') }}/.vimrc"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'
- name: Copy .tmux.conf
  ansible.builtin.template:
    src: "tmux.conf"
    dest: "{{ lookup('env', 'HOME') }}/.tmux.conf"
    owner: "{{ lookup('env', 'USER') }}"
    group: "{{ lookup('env', 'USER') }}"
    mode: '0755'

- name: Copy bin directory
  ansible.posix.synchronize:
    src: "./templates/bin"
    dest: "{{ lookup('env', 'HOME') }}/"
    recursive: true

- name: Change default shell
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh

- name: Add user to libvirt group
  ansible.builtin.user:
    append: true
    name: "{{ lookup('env', 'USER') }}"
    groups: libvirt
